FusoHorario:
  TimeZone: 'America/Sao_Paulo'
  Ajuste:
    Dias: 0
    Horas: 0
    Minutos: 0
    Segundos: 0

Debug:
 - 'All'
 - 'Others'
 - 'Task added'
 - 'Task removed'
 - 'Tasks removed'
 - 'Task enabled'
 - 'Task disabled'
 - 'Task Restarted'
 - 'Task running'
 - 'Task error execute'
 - 'Manager starting'
 - 'Manager stopping'
 - 'Manager next execution'
 - 'Manager none task'
 - 'Manager removing disabled commandTmpTasks'