Language: 'pt-br'
FusoHorario:
  TimeZone: 'America/Sao_Paulo'
  # Ajuste em milisegundos
  Ajuste: 0

Debug:
 - 'All'
 - 'Others'
 - 'Task added'
 - 'Task removed'
 - 'Tasks removed'
 - 'Task enabled'
 - 'Task disabled'
 - 'Task Restarted'
 - 'Task running'
 - 'Task error execute'
 - 'Manager starting'
 - 'Manager stopping'
 - 'Manager next execution'
 - 'Manager none task'
 - 'Manager removing disabled commandTmpTasks'